<h2>Where is the exception?</h2>
<p></p>
<p>Run the code you see below and view the stack trace:</p>
<pre><code class="language-kotlin">fun main() {
    val input = "110 111 32 101 114 114 111 114 32 59 41".split(" ")
    input.forEach { print(it.toInt().toChar()) }
}</code></pre>
<p>In which line of the code does the exception occur?</p>
